on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN_GITHUB_ACTIONS_ADMINISTRATOR }}
          aws-region: ap-northeast-1
      - uses: actions/setup-node@v4
        with:
          node-version: '21.2.0'
      - run: npm install
      - run: npm run build
      - run: tree dist
